name: ZMusicBox
version: 3.1.0
api: 3.15.0
author: Zzm
description: Play music in your server
main: ZMusicBox\ZMusicBox

commands:
  music:
    permission: ZMusicBox.music
    description: Manage the music in your server
    usage: /music <start|stop|next>

permissions:
  ZMusicBox:
    default: op
    description: ZMusicBox Commands
    children:
      ZMusicBox.music:
        default: op
        description: ZMusicBox Commands
