name: ZMusicBox
version: 3.0.0
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
author: Zzm
description: Play music in your server
main: ZMusicBox\ZMusicBox

commands:
 music:
  permission: ZMusicBox.music
  description: Manage the music in your server
  usage: /music <start|stop|next>

permissions:
 ZMusicBox:
  default: op
  description: ZMusicBox Commands
  children:
     ZMusicBox.music:
      default: op
      description: ZMusicBox Commands
    
